POST http://localhost:3000/videos
Content-Type: application/json

{
    "title": "Video bum",
    "description": "lorem",
    "duration": 180
}

###

GET http://localhost:3000/videos?search=bum

###

PUT http://localhost:3000/videos/
Content-Type: application/json

{
    "title": "Video 02",
    "description": "lorem 01",
    "duration": 180
}

###

DELETE http://localhost:3000/videos/55056bca-9b45-4f02-8ca4-9dcecab8ec11
